# Generated by Django 5.2.1 on 2026-07-24 10:48

import django_tiptap_suite.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_tiptap_suite.fields.HTMLField()),
            ],
        ),
    ]
